server:
  port: 8081

spring:
  application:
    name: QUIZ-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/eazybank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      import--check:
        enabled: false
        

        

#eureka.client.register-with-eureka=true
eureka:
 client:
  fetch-registry: true
  service-url.defaultZone: http://localhost:8761/eureka/
 instance:
  prefer-ip-address: false
  hostname: localhost
  
# Zipkin settings
#FOr prod we can reduce rate
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
 #tracing:
  #sampling:
   #probability: 1.0
   
jwt:
  secret: thisIsMySuperLongSecretKeyThatIsExactlySixtyFourBytesLong!!123456789122
  
#resilience4j:
#  bulkhead:
#    instances:
#      start-quiz-bulkhead:
#        maxConcurrentCalls: 2
#        maxWaitDuration: 0ms


 
#  config:
#    import: optional:configserver:http://localhost:9090
